services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.62.0
    ports:
      - '16686:16686'

  flags:
    container_name: flags
    image: wesha/flags:1.6.0
    command: server
    environment:
      - ENV=prod
      - NAME=flags
      - VERSION=1.6.0
      - HTTP_ADDRESS=:4000
      - API_KEYS=myflagstoken
      - TRACES_ADDRESS=jaeger:4318
      - FLAG_FORMAT=json
      - FILE_CLIENT=local
      - FILE_CLIENT_DIR=/nodejs
      - FILE_CLIENT_FILES=/flags.json
    volumes:
      - type: bind
        source: ./
        target: /nodejs/
    depends_on:
      - jaeger

  nodejs:
    container_name: nodejs
    build: service/.
    depends_on:
      - flags